language: ruby

rvm: 2.1.5

services:
  - redis

addons:
  postgresql: 9.3

cache: bundler

sudo: false

env:
  global:
    - COVERAGE=1
  matrix:
    - RAKE_TASK=spec
    - RAKE_TASK=rubocop

before_install: gem install bundler

before_script:
  - bundle exec rake db:create --trace
  - bundle exec rake db:structure:load --trace
  - env

script: ./build.sh $RAKE_TASK

matrix:
  allow_failures:
    - env: RAKE_TASK=rubocop
